[DEFAULT]
upstream-branch = stable
debian-branch = ubuntu/questing
upstream-tag = v%(version)s

[buildpackage]
submodules = true
ignore-new = true
pbuilder = true
dist = questing


[pq]
ignore-new = true
